version: "3.9"  
services:
  web:
    image: research-radar:current
    read_only: true
    restart: unless-stopped
    ports:
        - "8080:8080"
    environment: 
      DEBUG: true
    volumes:
        - type: bind
          source: ./data
          target: /opt/pharo/data